import { MD3LightTheme as PaperLightTheme, MD3DarkTheme as PaperDarkTheme, configureFonts } from 'react-native-paper';
import { colors, spacing, borderRadius, typography } from './colors';

const fontConfig = {
  fontFamily: 'System',
  fontWeightRegular: '400',
  fontWeightMedium: '500',
  fontWeightBold: '700',
};

export const lightTheme = {
  ...PaperLightTheme,
  colors: {
    ...PaperLightTheme.colors,
    primary: colors.primary,
    onPrimary: '#FFFFFF',
    primaryContainer: colors.primaryLight,
    onPrimaryContainer: colors.primaryDark,
    secondary: colors.secondary,
    onSecondary: '#FFFFFF',
    secondaryContainer: colors.secondaryLight,
    onSecondaryContainer: colors.secondaryDark,
    tertiary: colors.tertiary,
    onTertiary: '#FFFFFF',
    tertiaryContainer: colors.tertiaryLight,
    onTertiaryContainer: colors.tertiaryDark,
    error: colors.error,
    onError: '#FFFFFF',
    errorContainer: colors.errorLight,
    onErrorContainer: colors.errorDark,
    background: colors.background,
    onBackground: colors.text,
    surface: colors.surface,
    onSurface: colors.text,
    surfaceVariant: colors.border,
    onSurfaceVariant: colors.textSecondary,
    outline: colors.border,
    outlineVariant: colors.border,
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: colors.darkSurface,
    inverseOnSurface: colors.darkText,
    inversePrimary: colors.primaryLight,
  },
  fonts: configureFonts({ config: fontConfig }),
  roundness: borderRadius.md,
};

export const darkTheme = {
  ...PaperDarkTheme,
  colors: {
    ...PaperDarkTheme.colors,
    primary: colors.primary,
    onPrimary: '#000000',
    primaryContainer: colors.primaryDark,
    onPrimaryContainer: colors.primaryLight,
    secondary: colors.secondary,
    onSecondary: '#000000',
    secondaryContainer: colors.secondaryDark,
    onSecondaryContainer: colors.secondaryLight,
    tertiary: colors.tertiary,
    onTertiary: '#000000',
    tertiaryContainer: colors.tertiaryDark,
    onTertiaryContainer: colors.tertiaryLight,
    error: colors.error,
    onError: '#FFFFFF',
    errorContainer: colors.errorDark,
    onErrorContainer: colors.errorLight,
    background: colors.darkBackground,
    onBackground: colors.darkText,
    surface: colors.darkSurface,
    onSurface: colors.darkText,
    surfaceVariant: colors.darkBorder,
    onSurfaceVariant: colors.darkTextSecondary,
    outline: colors.darkBorder,
    outlineVariant: colors.darkBorder,
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: colors.surface,
    inverseOnSurface: colors.text,
    inversePrimary: colors.primaryLight,
  },
  fonts: configureFonts({ config: fontConfig }),
  roundness: borderRadius.md,
};

export { colors, spacing, borderRadius, typography } from './colors';