import {
  MD3LightTheme as PaperLightTheme,
  MD3DarkTheme as PaperDarkTheme,
  configureFonts,
} from 'react-native-paper';
import {
  BrandColors,
  Spacing,
  BorderRadius,
  Elevation,
  Typography,
  Animation,
  TouchTarget,
} from './tokens';

const fontConfig = {
  fontFamily: 'System',
  fontWeightRegular: '400',
  fontWeightMedium: '500',
  fontWeightBold: '700',
};

export const lightTheme = {
  ...PaperLightTheme,
  dark: false,
  colors: {
    ...PaperLightTheme.colors,
    primary: BrandColors.light.primary,
    onPrimary: BrandColors.light.onPrimary,
    primaryContainer: BrandColors.light.primaryContainer,
    onPrimaryContainer: BrandColors.light.onPrimaryContainer,
    secondary: BrandColors.light.secondary,
    onSecondary: BrandColors.light.onSecondary,
    secondaryContainer: BrandColors.light.secondaryContainer,
    onSecondaryContainer: BrandColors.light.onSecondaryContainer,
    tertiary: BrandColors.light.tertiary,
    onTertiary: BrandColors.light.onTertiary,
    tertiaryContainer: BrandColors.light.tertiaryContainer,
    onTertiaryContainer: BrandColors.light.onTertiaryContainer,
    error: BrandColors.light.error,
    onError: BrandColors.light.onError,
    errorContainer: BrandColors.light.errorContainer,
    onErrorContainer: BrandColors.light.onErrorContainer,
    background: BrandColors.light.background,
    onBackground: BrandColors.light.onBackground,
    surface: BrandColors.light.surface,
    onSurface: BrandColors.light.onSurface,
    surfaceVariant: BrandColors.light.surfaceVariant,
    onSurfaceVariant: BrandColors.light.onSurfaceVariant,
    outline: BrandColors.light.outline,
    outlineVariant: BrandColors.light.outlineVariant,
    surfaceContainerLow: BrandColors.light.surfaceContainerLow,
    surfaceContainerHigh: BrandColors.light.surfaceContainerHigh,
    surfaceContainerHighest: BrandColors.light.surfaceContainerHighest,
    inverseSurface: BrandColors.light.inverseSurface,
    inverseOnSurface: BrandColors.light.inverseOnSurface,
    inversePrimary: BrandColors.light.inversePrimary,
    shadow: BrandColors.light.shadow,
    scrim: BrandColors.light.scrim,
    surfaceDisabled: BrandColors.light.onSurface,
    onSurfaceDisabled: BrandColors.light.onSurface,
    backdrop: BrandColors.light.scrim,
  },
  fonts: configureFonts({ config: fontConfig }),
  roundness: BorderRadius.md,
  spacing: Spacing,
  elevation: Elevation,
  animation: Animation,
  touchTarget: TouchTarget,
};

export const darkTheme = {
  ...PaperDarkTheme,
  dark: true,
  colors: {
    ...PaperDarkTheme.colors,
    primary: BrandColors.dark.primary,
    onPrimary: BrandColors.dark.onPrimary,
    primaryContainer: BrandColors.dark.primaryContainer,
    onPrimaryContainer: BrandColors.dark.onPrimaryContainer,
    secondary: BrandColors.dark.secondary,
    onSecondary: BrandColors.dark.onSecondary,
    secondaryContainer: BrandColors.dark.secondaryContainer,
    onSecondaryContainer: BrandColors.dark.onSecondaryContainer,
    tertiary: BrandColors.dark.tertiary,
    onTertiary: BrandColors.dark.onTertiary,
    tertiaryContainer: BrandColors.dark.tertiaryContainer,
    onTertiaryContainer: BrandColors.dark.onTertiaryContainer,
    error: BrandColors.dark.error,
    onError: BrandColors.dark.onError,
    errorContainer: BrandColors.dark.errorContainer,
    onErrorContainer: BrandColors.dark.onErrorContainer,
    background: BrandColors.dark.background,
    onBackground: BrandColors.dark.onBackground,
    surface: BrandColors.dark.surface,
    onSurface: BrandColors.dark.onSurface,
    surfaceVariant: BrandColors.dark.surfaceVariant,
    onSurfaceVariant: BrandColors.dark.onSurfaceVariant,
    outline: BrandColors.dark.outline,
    outlineVariant: BrandColors.dark.outlineVariant,
    surfaceContainerLow: BrandColors.dark.surfaceContainerLow,
    surfaceContainerHigh: BrandColors.dark.surfaceContainerHigh,
    surfaceContainerHighest: BrandColors.dark.surfaceContainerHighest,
    inverseSurface: BrandColors.dark.inverseSurface,
    inverseOnSurface: BrandColors.dark.inverseOnSurface,
    inversePrimary: BrandColors.dark.inversePrimary,
    shadow: BrandColors.dark.shadow,
    scrim: BrandColors.dark.scrim,
    surfaceDisabled: BrandColors.dark.onSurface,
    onSurfaceDisabled: BrandColors.dark.onSurface,
    backdrop: BrandColors.dark.scrim,
  },
  fonts: configureFonts({ config: fontConfig }),
  roundness: BorderRadius.md,
  spacing: Spacing,
  elevation: Elevation,
  animation: Animation,
  touchTarget: TouchTarget,
};

export { BrandColors, Spacing, BorderRadius, Elevation, Typography, Animation, TouchTarget, IconSize } from './tokens';
export type { } from './tokens';