export const BrandColors = {
  light: {
    primary: '#22C55E',
    onPrimary: '#FFFFFF',
    primaryContainer: '#DCFCE7',
    onPrimaryContainer: '#14532D',
    secondary: '#3B82F6',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#DBEAFE',
    onSecondaryContainer: '#1E3A5F',
    tertiary: '#EF4444',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FEF2F2',
    onTertiaryContainer: '#7F1D1D',
    error: '#EF4444',
    onError: '#FFFFFF',
    errorContainer: '#FEF2F2',
    onErrorContainer: '#7F1D1D',
    background: '#FAFAFA',
    onBackground: '#18181B',
    surface: '#FFFFFF',
    onSurface: '#18181B',
    surfaceVariant: '#F4F4F5',
    onSurfaceVariant: '#52525B',
    outline: '#E4E4E7',
    outlineVariant: '#D4D4D8',
    surfaceContainerLow: '#FFFFFF',
    surfaceContainerHigh: '#F4F4F5',
    surfaceContainerHighest: '#E4E4E7',
    inverseSurface: '#27272A',
    inverseOnSurface: '#FAFAFA',
    inversePrimary: '#86EFAC',
    shadow: '#000000',
    scrim: '#000000',
  },
  dark: {
    primary: '#4ADE80',
    onPrimary: '#052E16',
    primaryContainer: '#14532D',
    onPrimaryContainer: '#DCFCE7',
    secondary: '#60A5FA',
    onSecondary: '#1E3A5F',
    secondaryContainer: '#1E3A5F',
    onSecondaryContainer: '#DBEAFE',
    tertiary: '#F87171',
    onTertiary: '#450A0A',
    tertiaryContainer: '#7F1D1D',
    onTertiaryContainer: '#FEF2F2',
    error: '#F87171',
    onError: '#450A0A',
    errorContainer: '#7F1D1D',
    onErrorContainer: '#FEF2F2',
    background: '#09090B',
    onBackground: '#FAFAFA',
    surface: '#18181B',
    onSurface: '#FAFAFA',
    surfaceVariant: '#27272A',
    onSurfaceVariant: '#A1A1AA',
    outline: '#3F3F46',
    outlineVariant: '#52525B',
    surfaceContainerLow: '#09090B',
    surfaceContainerHigh: '#18181B',
    surfaceContainerHighest: '#27272A',
    inverseSurface: '#E4E4E7',
    inverseOnSurface: '#18181B',
    inversePrimary: '#14532D',
    shadow: '#000000',
    scrim: '#000000',
  },
};

export const Spacing = {
  none: 0,
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const BorderRadius = {
  none: 0,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  full: 9999,
};

export const Elevation = {
  level0: 0,
  level1: 1,
  level2: 3,
  level3: 6,
  level4: 8,
  level5: 12,
};

export const Typography = {
  fontFamily: {
    regular: 'System',
    medium: 'System',
    bold: 'System',
  },
  fontSize: {
    displayLarge: 57,
    displayMedium: 45,
    displaySmall: 36,
    headlineLarge: 32,
    headlineMedium: 28,
    headlineSmall: 24,
    titleLarge: 22,
    titleMedium: 16,
    titleSmall: 14,
    bodyLarge: 16,
    bodyMedium: 14,
    bodySmall: 12,
    labelLarge: 14,
    labelMedium: 12,
    labelSmall: 11,
  },
  fontWeight: {
    regular: '400',
    medium: '500',
    bold: '700',
  },
  lineHeight: {
    displayLarge: 64,
    displayMedium: 52,
    displaySmall: 44,
    headlineLarge: 40,
    headlineMedium: 36,
    headlineSmall: 32,
    titleLarge: 28,
    titleMedium: 24,
    titleSmall: 20,
    bodyLarge: 24,
    bodyMedium: 20,
    bodySmall: 16,
    labelLarge: 20,
    labelMedium: 16,
    labelSmall: 14,
  },
  letterSpacing: {
    displayLarge: -0.25,
    displayMedium: 0,
    displaySmall: 0,
    headlineLarge: 0,
    headlineMedium: 0,
    headlineSmall: 0,
    titleLarge: 0,
    titleMedium: 0.15,
    titleSmall: 0.1,
    bodyLarge: 0.5,
    bodyMedium: 0.25,
    bodySmall: 0.4,
    labelLarge: 0.1,
    labelMedium: 0.5,
    labelSmall: 0.5,
  },
};

export const Animation = {
  duration: {
    short: 150,
    medium: 250,
    long: 350,
  },
  easing: {
    standard: 'cubic-bezier(0.2, 0.0, 0, 1.0)',
    accelerate: 'cubic-bezier(0.4, 0.0, 1, 1)',
    decelerate: 'cubic-bezier(0.0, 0.0, 0.2, 1)',
    emphasized: 'cubic-bezier(0.2, 0.0, 0, 1)',
  },
};

export const IconSize = {
  xs: 16,
  sm: 20,
  md: 24,
  lg: 28,
  xl: 32,
  xxl: 36,
};

export const TouchTarget = {
  minSize: 48,
  comfortable: 56,
};